### ISSUE TITLE
Picture's got wrong name

### ISSUE THREAD

**Issue by jusjusjus** [jusjusjus/wxArt#18]
Die Namen der Bilder sind zt falsch.  Die Modelle in /models/<bildname>.model muss den selben Namen haben)

**Comment by bluens** [comment]
Resolved. Will be pushed after lunch

**Comment by philmu** [comment]
https://m.youtube.com/watch?v=9D-QD_HIfjAVon meinem Huawei-Mobiltelefon gesendet-------- Originalnachricht --------Betreff: Re: [jusjusjus/wxArt] Picture's got wrong name (#18)Von: bluens An: jusjusjus/wxArt Cc: Resolved. Will be pushed after lunch

—You are receiving this because you are subscribed to this thread.Reply to this email directly, view it on GitHub, or mute the thread.


  
  




{"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/jusjusjus/wxArt","title":"jusjusjus/wxArt","subtitle":"GitHub repository","main_image_url":"https://cloud.githubusercontent.com/assets/143418/17495839/a5054eac-5d88-11e6-95fc-7290892c7bb5.png","avatar_image_url":"https://cloud.githubusercontent.com/assets/143418/15842166/7c72db34-2c0b-11e6-9aed-b52498112777.png","action":{"name":"Open in GitHub","url":"https://github.com/jusjusjus/wxArt"}},"updates":{"snippets":[{"icon":"PERSON","message":"@bluens in #18: Resolved. Will be pushed after lunch"}],"action":{"name":"View Issue","url":"https://github.com/jusjusjus/wxArt/issues/18#issuecomment-250127690"}}}

**Comment by bluens** [comment]
pushed, waiting for merge

**Comment by jusjusjus** [comment]
Vielen Dank.  Fehlt nur noch 'Unbekannter_Künstler-Fur.jpg'.
